### ISSUE TITLE
'FakeTimeoutManager' object has no attribute 'reset'

### ISSUE THREAD

**Issue by richtier** [kangasta/resettabletimer#2]
Thanks for the library :)

I'm using `FakeTimeoutManager` as a test double.

My code calls `timer.reset()`

> AttributeError: 'FakeTimeoutManager' object has no attribute 'reset'

`FakeTimeoutManager.reset` does not exist.

Is this on purpose? if not I'm happy to make a PR adding it

**Comment by kangasta** [comment]
I have been using FakeTimer to Mock Pythons default timer implementation inside ResettableTimer, which is why I didn't include `reset()` in FakeTimer.

However, reset method would also be useful in FakeTimer. PR welcome!
